version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: module
    ports:
      - "3306:3306"
    networks:
      - my-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network

  eureka-server:
    build:
      context: ./EdgeMicroServices
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - my-network

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - my-network
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "9012:9012"
    networks:
      - my-network
    depends_on:
      - config-server
      - eureka-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  matiere-ms:
    build:
      context: ./matiere-ms
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    networks:
      - my-network
    depends_on:
      - gateway
      - config-server
      - eureka-server
      - mongodb
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/matiere

  module-ms:
    build:
      context: ./module-ms
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - my-network
    depends_on:
      - gateway
      - config-server
      - eureka-server
      - mysql
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/module?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

networks:
  my-network:
    driver: bridge
